### PR TITLE
ENH PHP 8.1 Compatibility

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-fulltextsearch/issues/323

Tag 1.0.2 when merged

CI hasn't yet been added to repo - though you can see the CI running on the creative-commoners repo - https://github.com/creative-commoners/solr-php-client/actions

### CODE REVIEW

**Review by GuySartorelli — COMMENTED** [review]
All good, just gotta add some CI

**Comment by emteknetnz** [comment]
@GuySartorelli Have updated, tests are green on the creative-commoners repo

**Review by GuySartorelli — APPROVED** [review]
Looks good. Apparently future PRs will run the action (and therefore the tests) - they're passing in CC anyway so I'm happy with it.

**Comment by ChloeSartorelli** [comment]
@emteknetnz [v1.0.2](https://github.com/silverstripe/solr-php-client/releases/tag/v1.0.2) and manually updated packagist

**Pull request merged**
